/**
 * Seed quotes for "Quote of the day" banner. Structure supports 100,000+ quotes.
 * Add more by inserting into the Quote collection or importing from external sources.
 */
export const SEED_QUOTES = [
  { text: 'A room without books is like a body without a soul.', author: 'Marcus Tullius Cicero' },
  { text: 'The only thing you absolutely have to know is the location of the library.', author: 'Albert Einstein' },
  { text: 'Books are a uniquely portable magic.', author: 'Stephen King' },
  { text: 'There is no friend as loyal as a book.', author: 'Ernest Hemingway' },
  { text: 'The more that you read, the more things you will know.', author: 'Dr. Seuss' },
  { text: 'A reader lives a thousand lives before he dies.', author: 'George R.R. Martin' },
  { text: 'I have always imagined that Paradise will be a kind of library.', author: 'Jorge Luis Borges' },
  { text: 'That\'s the thing about books. They let you travel without moving your feet.', author: 'Jhumpa Lahiri' },
  { text: 'One book, one pen, one child can change the world.', author: 'Malala Yousafzai' },
  { text: 'Books are the quietest and most constant of friends.', author: 'Charles W. Eliot' },
  { text: 'Reading is to the mind what exercise is to the body.', author: 'Joseph Addison' },
  { text: 'The library is not a shrine for the worship of books. It is a place where books can be free.', author: 'Richard Ovenden' },
  { text: 'Libraries were full of ideas—perhaps the most dangerous and powerful of all weapons.', author: 'Sarah J. Maas' },
  { text: 'A book is a dream that you hold in your hands.', author: 'Neil Gaiman' },
  { text: 'Books are mirrors: you only see in them what you already have inside you.', author: 'Carlos Ruiz Zafón' },
  { text: 'We read to know we are not alone.', author: 'C.S. Lewis' },
  { text: 'The best moments in reading are when you come across something that changes you.', author: 'R.J. Palacio' },
  { text: 'Books are the plane, and the train, and the road. They are the destination.', author: 'Anna Quindlen' },
  { text: 'Reading gives us someplace to go when we have to stay where we are.', author: 'Mason Cooley' },
  { text: 'A library is the delivery room for the birth of ideas.', author: 'Norman Cousins' },
  { text: 'Today a reader, tomorrow a leader.', author: 'Margaret Fuller' },
  { text: 'The book you don\'t read won\'t help.', author: 'Jim Rohn' },
  { text: 'No two persons ever read the same book.', author: 'Edmund Wilson' },
  { text: 'Books are the treasured wealth of the world.', author: 'Henry David Thoreau' },
  { text: 'Reading is essential for those who seek to rise above the ordinary.', author: 'Jim Rohn' },
  { text: 'A book is a gift you can open again and again.', author: 'Garrison Keillor' },
  { text: 'Libraries store the energy that fuels the imagination.', author: 'Sidney Sheldon' },
  { text: 'Books are the compasses and telescopes and sextants of our minds.', author: 'Lee Iacocca' },
  { text: 'The reading of all good books is like conversation with the finest minds.', author: 'René Descartes' },
  { text: 'So many books, so little time.', author: 'Frank Zappa' },
  { text: 'A book is a device to ignite the imagination.', author: 'Alan Bennett' },
  { text: 'Books are the ultimate Dumpees: put them down and they\'ll wait for you forever.', author: 'John Green' },
  { text: 'Reading is a conversation. All books talk. But a good book listens as well.', author: 'Mark Haddon' },
  { text: 'Books are the quietest and most constant of friends.', author: 'Charles W. Eliot' },
  { text: 'I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.', author: 'Groucho Marx' },
  { text: 'There is no substitute for books in the life of a child.', author: 'May Ellen Chase' },
  { text: 'A house without books is like a room without windows.', author: 'Heinrich Mann' },
  { text: 'Books serve to show a man that those original thoughts of his aren\'t very new after all.', author: 'Abraham Lincoln' },
  { text: 'The world belongs to those who read.', author: 'Rick Holland' },
  { text: 'Books are the carriers of civilization.', author: 'Barbara Tuchman' },
  { text: 'Think before you speak. Read before you think.', author: 'Fran Lebowitz' },
  { text: 'Reading is a basic tool in the living of a good life.', author: 'Joseph Addison' },
  { text: 'A book is the most effective weapon against intolerance and ignorance.', author: 'Lyndon B. Johnson' },
  { text: 'Books are the training weights of the mind.', author: 'Epictetus' },
  { text: 'The greatest gift is a passion for reading.', author: 'Elizabeth Hardwick' },
  { text: 'Books are the mirrors of the soul.', author: 'Virginia Woolf' },
  { text: 'Reading is escape, and the opposite of escape; it\'s a way to make contact with reality.', author: 'Nora Ephron' },
  { text: 'A library is the only place you can go and be free in this world.', author: 'Ray Bradbury' },
  { text: 'Books are the bees which carry the quickening pollen from one to another mind.', author: 'James Russell Lowell' },
  { text: 'The more you read, the more things you will know. The more that you learn, the more places you\'ll go.', author: 'Dr. Seuss' },
  { text: 'A book is a garden, an orchard, a storehouse, a party, a company by the way, a counselor, a multitude of counselors.', author: 'Charles Baudelaire' },
  { text: 'Books are the perfect entertainment: no commercials, no batteries, hours of enjoyment.', author: 'Stephen King' },
  { text: 'Reading brings us unknown friends.', author: 'Honoré de Balzac' },
  { text: 'Books are the stepping stones for human progress.', author: 'Carolyn Reidy' },
  { text: 'A book is a magical thing that lets you travel to faraway places without leaving your chair.', author: 'Anonymous' },
  { text: 'The best advice I ever got was that knowledge is power and to keep reading.', author: 'David Bailey' },
  { text: 'Books open your mind, broaden your mind, and strengthen you as nothing else can.', author: 'William Feather' },
  { text: 'Reading is a discount ticket to everywhere.', author: 'Mary Schmich' },
  { text: 'A library is a hospital for the mind.', author: 'Anonymous' },
  { text: 'Books are the quietest and most constant of friends.', author: 'Charles W. Eliot' },
  { text: 'The person who does not read has no advantage over the person who cannot read.', author: 'Mark Twain' },
  { text: 'Books are the ultimate escape—they take you to new worlds without leaving your chair.', author: 'Anonymous' },
  { text: 'Reading is to the mind what exercise is to the body and prayer is to the soul.', author: 'Matthew Kelly' },
  { text: 'A book is a dream that you hold in your hands.', author: 'Neil Gaiman' },
  { text: 'Libraries are the memory of mankind.', author: 'Isaac Asimov' },
  { text: 'Books are the plane, and the train, and the road.', author: 'Anna Quindlen' },
  { text: 'The reading of all good books is like a conversation with the finest minds of past centuries.', author: 'René Descartes' },
  { text: 'Books are the mirrors of the soul.', author: 'Virginia Woolf' },
  { text: 'A book is a gift you can open again and again.', author: 'Garrison Keillor' },
  { text: 'Reading gives us someplace to go when we have to stay where we are.', author: 'Mason Cooley' },
  { text: 'Books are the treasured wealth of the world and the fit inheritance of generations and nations.', author: 'Henry David Thoreau' },
  { text: 'The more you read, the more things you will know. The more that you learn, the more places you\'ll go.', author: 'Dr. Seuss' },
  { text: 'A room without books is like a body without a soul.', author: 'Marcus Tullius Cicero' },
  { text: 'Books are a uniquely portable magic.', author: 'Stephen King' },
  { text: 'There is no friend as loyal as a book.', author: 'Ernest Hemingway' },
  { text: 'I have always imagined that Paradise will be a kind of library.', author: 'Jorge Luis Borges' },
  { text: 'That\'s the thing about books. They let you travel without moving your feet.', author: 'Jhumpa Lahiri' },
  { text: 'One book, one pen, one child can change the world.', author: 'Malala Yousafzai' },
  { text: 'We read to know we are not alone.', author: 'C.S. Lewis' },
  { text: 'The best moments in reading are when you come across something that changes you.', author: 'R.J. Palacio' },
  { text: 'A book is a device to ignite the imagination.', author: 'Alan Bennett' },
  { text: 'Books are the quietest and most constant of friends.', author: 'Charles W. Eliot' },
  { text: 'Libraries store the energy that fuels the imagination.', author: 'Sidney Sheldon' },
  { text: 'The world belongs to those who read.', author: 'Rick Holland' },
  { text: 'Think before you speak. Read before you think.', author: 'Fran Lebowitz' },
  { text: 'Books are the carriers of civilization.', author: 'Barbara Tuchman' },
  { text: 'Reading is a basic tool in the living of a good life.', author: 'Joseph Addison' },
  { text: 'The greatest gift is a passion for reading.', author: 'Elizabeth Hardwick' },
  { text: 'Books are the mirrors of the soul.', author: 'Virginia Woolf' },
  { text: 'A library is the only place you can go and be free in this world.', author: 'Ray Bradbury' },
  { text: 'Books are the bees which carry the quickening pollen from one to another mind.', author: 'James Russell Lowell' },
  { text: 'Reading brings us unknown friends.', author: 'Honoré de Balzac' },
  { text: 'Books are the stepping stones for human progress.', author: 'Carolyn Reidy' },
  { text: 'The best advice I ever got was that knowledge is power and to keep reading.', author: 'David Bailey' },
  { text: 'Books open your mind, broaden your mind, and strengthen you as nothing else can.', author: 'William Feather' },
  { text: 'Reading is a discount ticket to everywhere.', author: 'Mary Schmich' },
  { text: 'The person who does not read has no advantage over the person who cannot read.', author: 'Mark Twain' },
  { text: 'Reading is to the mind what exercise is to the body and prayer is to the soul.', author: 'Matthew Kelly' },
  { text: 'Libraries are the memory of mankind.', author: 'Isaac Asimov' },
  { text: 'Knowledge is power. Information is liberating. Education is the premise of progress.', author: 'Kofi Annan' },
  { text: 'The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.', author: 'Brian Herbert' },
  { text: 'Learning is a treasure that will follow its owner everywhere.', author: 'Chinese Proverb' },
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' },
  { text: 'The beautiful thing about learning is that nobody can take it away from you.', author: 'B.B. King' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Develop a passion for learning. If you do, you will never cease to grow.', author: 'Anthony J. D\'Angelo' },
  { text: 'Learning is not attained by chance, it must be sought for with ardor.', author: 'Abigail Adams' },
];
